name: 'Coverlet coverage test'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  output:  # id of input
    description: 'output filename'
    required: true
    default: './lcov.info'
  outputFormat:
    description: 'output format : lcov, json, opencover, cobertura, teamcity (see coverlet documentation)' 
    required: true
    default : 'lcov'
  testProject:
    description: 'path to unit test project from repository root'    
    required: true
  threshold:
    description: 'threshold below which tests fail.'
    required: false
outputs:
  coverageFile:
    description: 'path to the generated coverage file'     
runs:
  using: 'node14'
  main: 'dist/index.js'
